
class Colors:
    DARKER_GREEN = "#CCD5AE"
    LIGHT_GREEN = "#E9EDC9"
    BONE = "#FEFAE0"
    CREAM = "#FAEDCD"
    BROWN = "#D4A373"
    YELLOW = "#EE9B00"
    YELLOWISH = "#FFB703"
    BORDER_BROWN = "#BC6C25"

    ROW_LIGHT_GREEN = "#A7C957"
    ROW_DARK_GREEN = "#6A994E"

    CALENDAR_DARK_GREEN = "#8CB369"
    CALENDAR_MID_GREEN = "#6A994E"
    CALENDAR_LIGHT_GREEN = "#A7C957"
    CALENDAR_BORDER_GREEN = "#386641"
    CALENDAR_WHITE = "#F2E8CF"
    CALENDAR_RED = "#BC4749"
    CALENDAR_OTHERMONTH = "#D8F3DC"
    CALENDAR_OTHERMONTHWEEKEND = "#B7E4C7"